name: Check BTC price and notify

on:
  schedule:
    - cron: "* * * * *" # every minute
  workflow_dispatch:

jobs:
  check-btc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Restore last ATH cache
      uses: actions/cache@v3
      id: cache-last-ath
      with:
        path: last_ath.txt
        key: btc-last-ath-${{ runner.os }}-${{ hashFiles('last_ath.txt') }}
        restore-keys: |
          btc-last-ath-${{ runner.os }}-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run BTC price checker
      env:
        GROUPME_BOT_ID: ${{ secrets.GROUPME_BOT_ID }}
      run: |
        python check_btc.py

    - name: Save updated ATH cache
      uses: actions/cache@v3
      with:
        path: last_ath.txt
        key: btc-last-ath-${{ runner.os }}-${{ hashFiles('last_ath.txt') }}

