name: Check BTC price and notify

on:
  schedule:
    - cron: "* * * * *"  # every minute
  workflow_dispatch:

jobs:
  check-btc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore last ATH cache
        id: cache
        uses: actions/cache@v3
        with:
          path: last_ath.txt
          key: btc-last-ath

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BTC checker
        env:
          GROUPME_BOT_ID: ${{ secrets.GROUPME_BOT_ID }}
        run: python check_btc.py

      - name: Save updated ATH file back to cache
        uses: actions/cache@v3
        with:
          path: last_ath.txt
          key: btc-last-ath
